### PR TITLE
Add support for compose file version 3

### PR DESCRIPTION
**Pull request by robertgzr**

### CODE REVIEW

**Comment by robertgzr** [comment]
@Page- @pdcastro do you know why we have circle ci in here? those jobs seem to do the same `npm install + build` as our CI

**Comment by dfunckt** [comment]
@robertgzr I don't think balena CI existed when this repository was last updated. It would be great if you could spend the time to move it over our CI (and maybe also rename the repo? :)

**Comment by robertgzr** [comment]
@balena-ci rebase

**Comment by robertgzr** [comment]
let's go with #59 for now and see if we need to revive this effort at some later point

**Pull request closed without merging**
